name: notify builder

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  dispatch-builder:
    runs-on: ubuntu-latest
    steps:
      - name: dispatch to build workflow
        env:
          TARGET_REPO: ${{ secrets.BUILDER_REPO }}
          TOKEN: ${{ secrets.BUILDER_PAT }}
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${TARGET_REPO}/dispatches \
            -d '{"event_type":"guide-updated","client_payload":{"ref":"'"${GITHUB_REF}"'","sha":"'"${GITHUB_SHA}"'"}}'
